language: rust
matrix:
  fast_finish: true
  include:
    - name: stable
      rust: stable
      env:
        - TRAVIS_DEPLOY_JOB=1 DOCKER_COMPOSE_VERSION=1.22.0 RUST_LOG=arangors=trace
    - name: cargo doc
      rust: stable
      script:
        - RUSTDOCFLAGS=-Dwarnings cargo doc --all --no-deps
#  cargo: true
#  directories:
#    - /var/lib/docker

sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.22.0 RUST_LOG=arangors=trace

addons:
  apt:
    packages:
      - binutils-dev
      - cmake
      - docker-ce
      - gcc
      - libcurl4-openssl-dev
      - libdw-dev
      - libelf-dev
      - libiberty-dev

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker --version
  - docker-compose --version
  - docker-compose up -d
  - sleep 30
  - docker container ls
  - docker-compose logs

before_script:
  - bash tests/init_db.sh
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo build
  - cargo test
  - cargo build --no-default-features --features "rocksdb mmfiles cluster enterprise" --lib
  - cargo test --no-default-features --features "rocksdb mmfiles cluster enterprise" --lib
  - cargo build --no-default-features --features "rocksdb mmfiles cluster enterprise blocking"  --lib
  - cargo test --no-default-features --features "rocksdb mmfiles cluster enterprise blocking" --lib
  - cargo build --no-default-features --features "rocksdb mmfiles cluster enterprise reqwest_async"
  - cargo test --no-default-features --features "rocksdb mmfiles cluster enterprise reqwest_async"
  - cargo build --no-default-features --features "rocksdb mmfiles cluster enterprise reqwest_blocking"
  - cargo test --no-default-features --features "rocksdb mmfiles cluster enterprise reqwest_blocking"
  - cargo build --no-default-features --features "rocksdb mmfiles cluster enterprise surf_async"
  - cargo test --no-default-features --features "rocksdb mmfiles cluster enterprise surf_async"

notifications:
  email:
    on_success: never
deploy:
  provider: cargo
  token:
    secure: s9JGgM/tZni8ZNl0/J9T49pFph0Tl4SOjIklH7OhROZ/5iFdomeTm7ymLUqQ4H2sWVZfmEk4pgk5fMdvFxYNBy3bfcmRN2BDyJCoET+adxeGw4f5i2odUQfnEAjAp042SzYMZrcEinpsTtGTDk/+Ie6C3J3U2tWZKeEXpDKemHrkX89R7UpKrkZEaLmIReQprdGA1crD30xq5kcBCfH61wyJb37Xlp5lRHsQWl7ubY4HScrlOr6HudXAzrWM5O2sl+XV7YLh1OG+u0IPxJROMownkwyZMSF9Y2RH7hk30hGl4uSYA83BbcEhXN2tR+0RBRGHQojJl81Vd6bwUdY8Y8QgCJ2n/JmGOZ/cIRgkFkO5fSSZeAl36FTY5xcswGJqLxsT8s6kKz/m2OFL6lQ5IQ+3EiQLtl8uL2x5VYiitK4vGcoMPL72oovqCQSda4AM6RF0vDkdtLuZc1+FmDWTCGPO73j20s2UxgI/cCrZS9lhRmW4MkgU1U4NbhkiZn3hA0NrFsj3m5gQP2edacjHaPYv0WzpYEGQIa1b6SO3cli3YFxkdFSRdZaPbV85b9Y9HD1I2So1nU4nEJeT/i33ccloEUIrA7GG+lTOHY7POnYNdfI/BHgshIZdhgueZj011NjShVREWu4uJWaHakEIfLRZW+zKg6/zDR0oNYtfzMU=
  on:
    tags: true
    branch: master
    condition: "$TRAVIS_DEPLOY_JOB = 1"
